apiVersion: v1
kind: PersistentVolume
metadata:
  name: yolo_volume
  labels:
    app: yolo
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  gcePersistentDisk:
    pdName: gke-yoloipk8s-default-pool-22f70666-2gpt 
    fsType: ext4


---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: yolo_volume
  labels:
    app: yolo
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi